In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns = ['cgpa', 'profile_score', 'lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow
from tensorflow import keras 
from keras import Sequential
from keras.layers import Dense

C:\Users\LAPTOP\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [6]:
model = Sequential()

model.add(Dense(2,activation = 'linear', input_dim = 2))
model.add(Dense(1,activation = 'linear'))

C:\Users\LAPTOP\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.02768064, -1.1629646 ],
        [ 0.64340436, -0.25739795]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.08676076],
        [-0.04172027]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]], dtype = np.float32),
              np.array([0,0], dtype = np.float32),
              np.array([[0.1],[0.1]], dtype = np.float32),
              np.array([0], dtype = np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
optimizers = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer = optimizers)

In [12]:
model.fit(df.iloc[:,0:-1].values, df.iloc[:,-1].values, epochs =75, verbose = 1, batch_size = 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 27.8792
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.5694
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 27.2355
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.9024 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.5453
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.2100
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.8108
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4235 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0338 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6353 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2494 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.7906 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.3478
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.9391 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 22.4524
Epoch 16/75
4/4 ━━━

In [14]:
model.get_weights()

[array([[0.3733241, 0.3733241],
        [0.3655836, 0.3655836]], dtype=float32),
 array([0.2721749, 0.2721749], dtype=float32),
 array([[0.3727869],
        [0.3727869]], dtype=float32),
 array([0.20483829], dtype=float32)]