In [1]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

C:\Users\LAPTOP\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [5]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [14]:
from keras.layers import *
from keras import Sequential

embedding_dim = 50  
max_sequence_length = 5
model = Sequential([
    Embedding(input_dim=18, output_dim=embedding_dim, input_length=max_sequence_length)

])
model.add(Embedding(17,output_dim=2))
model.build(input_shape=(None, 5))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 5, 50)          │           900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_4 (Embedding)         │ (None, 5, 50, 2)       │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 934 (3.65 KB)

 Trainable params: 934 (3.65 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile('adam','accuracy')

In [16]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
[[[[ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   ...
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]]

  [[ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   ...
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]]

  [[ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   ...
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]]

  [[ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   ...
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]]

  [[ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   ...
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]
   [ 0.01464159 -0.01030134]]]


 [[[ 0.01464159 -0.01030134]
   [ 0.01464159

In [18]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [28]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [29]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [30]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_shape=(50,)))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])


In [32]:
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - acc: 0.5943 - loss: 0.6434 - val_acc: 0.7791 - val_loss: 0.4690
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - acc: 0.8125 - loss: 0.4210 - val_acc: 0.7966 - val_loss: 0.4554
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 15ms/step - acc: 0.8604 - loss: 0.3335 - val_acc: 0.7804 - val_loss: 0.4653
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - acc: 0.8839 - loss: 0.2905 - val_acc: 0.8024 - val_loss: 0.4837
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 15ms/step - acc: 0.9037 - loss: 0.2521 - val_acc: 0.7953 - val_loss: 0.5325
